FROM mcr.microsoft.com/windows/nanoserver:ltsc2022 as runtime
FROM golang:1.20 as builder


COPY install-plugin.ps1 ./
COPY RanchergMSACredentialProvider.dll ./

ENV GOPATH=

COPY go.mod go.sum main.go ./

RUN go mod download

RUN go build -o main.exe

FROM runtime

COPY --from=builder main.exe .

ENTRYPOINT ["main.exe"]