apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: gmsa-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gmsa-provider
  template:
    metadata:
      labels:
        app: gmsa-provider
    spec:
      serviceAccountName: rancher-windows-gmsa
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - name: provider
          image: harrisonwaffel/gmsa:latest
          securityContext:
            windowsOptions:
              hostProcess: true
              runAsUserName: "NT AUTHORITY\\Local service"
          env:
            - name: ACTIVE_DIRECTORY
              value: {{ .Values.activeDirectory.name }}
            - name: RELEASE_NAMESPACE
              value: {{ .Release.Namespace }}
