apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rancher-gmsa-provider-daemonset
  namespace: {{ .Release.Namespace }}
  labels:
    app: gmsa-provider
spec:
  selector:
    matchLabels:
      app: gmsa-provider
  template:
    metadata:
      labels:
        app: gmsa-provider
    spec:
      serviceAccountName: {{ .Release.Name }}-gmsa-service-account
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - name: provider
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          volumeMounts:
            - mountPath: /var/lib/rancher/gmsa/{{ .Release.Namespace }}/container/ssl/server
              name: server-cert
            - mountPath: /var/lib/rancher/gmsa/{{ .Release.Namespace }}/container/ssl/client
              name: client-cert
            - mountPath: /var/lib/rancher/gmsa/{{ .Release.Namespace }}/container/ssl/ca
              name: root-ca
          securityContext:
            windowsOptions:
              hostProcess: true
              runAsUserName: "NT AUTHORITY\\SYSTEM"
          env:
            - name: ACTIVE_DIRECTORY
              value: {{ .Release.Namespace }}
            - name: RELEASE_NAMESPACE
              value: {{ .Release.Namespace }}
      # projected volumes behave differently on windows, so we can't use them here https://kubernetes.io/docs/concepts/storage/projected-volumes/#windows
      volumes:
        - name: root-ca
          secret:
            secretName: {{ .Release.Name }}-root-cert
        - name: server-cert
          secret:
            secretName: {{ .Values.certificates.serverSecretName }}
        - name: client-cert
          secret:
            secretName: {{ .Values.certificates.clientSecretName }}
