{{ template "cert-manager.apiversion" . }}
kind: Certificate
metadata:
  name: {{ .Release.Name }}-provider-cert
  namespace: {{ .Release.Namespace }}
  labels: {{ include "gmsa.chartref" . | nindent 4 }}
spec:
  subject:
    organizations:
      - Rancher
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
    - cert sign
  dnsNames:
    - localhost
  issuerRef:
    kind: Issuer
    name: {{ .Release.Name }}
  secretName: {{ .Values.certificates.serverSecretName }}
  isCA: false
---
{{ template "cert-manager.apiversion" . }}
kind: Certificate
metadata:
  name: {{ .Release.Name }}-client-cert
  namespace: {{ .Release.Namespace }}
  labels: {{ include "gmsa.chartref" . | nindent 4 }}
spec:
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
    - cert sign
  subject:
    organizations:
      - Rancher
  dnsNames:
    - localhost
  issuerRef:
    kind: Issuer
    name: {{ .Release.Name }}
  secretName: {{ .Values.certificates.clientSecretName }}
  isCA: false
---
{{ template "cert-manager.apiversion" . }}
kind: Issuer
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "gmsa.chartref" . | nindent 4 }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: example@example.com
    name: letsencrypt-staging
