{{ template "cert-manager.apiversion" . }}
kind: Issuer
metadata:
  name: {{ .Release.Name }}-bootstrap
  namespace: {{ .Release.Namespace }}
  labels: {{ include "gmsa.chartref" . | nindent 4 }}
spec:
  selfSigned: {}

---

{{ template "cert-manager.apiversion" . }}
kind: Certificate
metadata:
  name: {{ .Release.Name }}-root-cert
  namespace: {{ .Release.Namespace }}
  labels: {{ include "gmsa.chartref" . | nindent 4 }}
spec:
  isCA: true
  secretName: {{ .Release.Name }}-root-cert
  commonName: rancher-gmsa-{{.Release.Name}}-root-certificate
  privateKey:
    algorithm: RSA
    size: 4096
    encoding: PKCS8
  issuerRef:
    name: {{ .Release.Name }}-bootstrap
    kind: Issuer

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-root-issuer
  namespace: {{ .Release.Namespace }}
spec:
  subject:
    organizations:
      - rancher-gmsa-{{ .Release.Name }}
  ca:
    secretName: {{ .Release.Name }}-root-cert

---

{{ template "cert-manager.apiversion" . }}
kind: Certificate
metadata:
  name: {{ .Release.Name }}-provider-cert
  namespace: {{ .Release.Namespace }}
  labels: {{ include "gmsa.chartref" . | nindent 4 }}
spec:
  subject:
    organizations:
      - rancher-gmsa-{{ .Release.Name }}
  usages:
    - server auth
  dnsNames:
    - https://localhost
    - localhost
  issuerRef:
    kind: Issuer
    name: {{ .Release.Name }}-root-issuer
  secretName: {{ .Values.certificates.serverSecretName }}
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gmsa-pkcs12-secret
  namespace: {{ .Release.Namespace }}
stringData:
  CertificatePassword: "SOME_PASSWORD_HERE"

---

{{ template "cert-manager.apiversion" . }}
kind: Certificate
metadata:
  name: {{ .Release.Name }}-client-cert
  namespace: {{ .Release.Namespace }}
  labels: {{ include "gmsa.chartref" . | nindent 4 }}
spec:
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key: CertificatePassword
        name: {{ .Release.Name }}-gmsa-pkcs12-secret
  subject:
    organizations:
      - rancher-gmsa-{{ .Release.Name }}
  dnsNames:
    - https://localhost
    - localhost
  usages:
    - client auth
  issuerRef:
    kind: Issuer
    name: {{ .Release.Name }}-root-issuer
  secretName: {{ .Values.certificates.clientSecretName }}
