# this just serves as an example
apiVersion: v1
kind: Secret
metadata:
  name: test
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: dXNlcgo=
  password: cGFzc3dvcmQK
  domainName: dGVzdC5jb20K
