apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rancher-gmsa-provider-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: gmsa-provider
spec:
  selector:
    matchLabels:
      app: gmsa-provider
  template:
    metadata:
      labels:
        app: gmsa-provider
    spec:
      serviceAccountName: rancher-windows-gmsa
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - name: provider
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          volumeMounts:
            - mountPath: /var/lib/rancher/gmsa/{{ .Values.activeDirectory.name }}/container/ssl/server
              name: server-cert
            - mountPath: /var/lib/rancher/gmsa/{{ .Values.activeDirectory.name }}/container/ssl/client
              name: client-cert
          securityContext:
            windowsOptions:
              hostProcess: true
              runAsUserName: "NT AUTHORITY\\Local service"
          env:
            - name: ACTIVE_DIRECTORY
              value: {{ .Values.activeDirectory.name }}
            - name: RELEASE_NAMESPACE
              value: {{ .Release.Namespace }}
      # projected volumes behave differently on windows, so we can't use them here https://kubernetes.io/docs/concepts/storage/projected-volumes/#windows
      volumes:
        - name: server-cert
          secret:
            secretName: {{ .Values.certificates.serverSecretName }}
        - name: client-cert
          secret:
            secretName: {{ .Values.certificates.clientSecretName }}
