# the service account for the webhook
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-gmsa-service-account
  namespace: {{ .Release.Namespace }}
  labels: {{ include "gmsa.chartref" . | nindent 4 }}
