apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gmsa-plugin-manager-daemonset
  labels:
    app: gmsa-plugin-manager
spec:
  selector:
    matchLabels:
      app: gmsa-plugin-manager
  template:
    metadata:
      labels:
        app: gmsa-plugin-manager
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: windows
      initContainers:
        - name: installer
          args:
            - {{ .Values.action }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
          securityContext:
            windowsOptions:
              hostProcess: true
              runAsUserName: "NT AUTHORITY\\SYSTEM"
      containers:
        - name: plugin-manager
          args:
            - pause
          image: rancher/mirrored-pause:3.7
          securityContext:
            windowsOptions:
              hostProcess: true
              runAsUserName: "NT AUTHORITY\\SYSTEM"
          imagePullPolicy: IfNotPresent
