apiVersion: v2
name: gmsa-provider
description: Simple Chart
version: 0.0.0
appVersion: 0.0.0
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/kube-version: '>= 1.24.0-0 < 1.28.0-0'
maintainers:
  - email: example@example.com
    name: test
