apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gmsa-plugin-manager-deployment
  labels:
    app: gmsa-plugin-manager
spec:
  selector:
    matchLabels:
      app: gmsa-plugin-manager
  template:
    metadata:
      labels:
        app: gmsa-plugin-manager
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - name: plugin-manager
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          securityContext:
            windowsOptions:
              hostProcess: true
              runAsUserName: "NT AUTHORITY\\SYSTEM"
