FROM mcr.microsoft.com/windows/nanoserver:ltsc2022 as runtime
FROM golang:1.20 as builder

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue';"]

WORKDIR /app

ENV GOPATH=

COPY go.mod go.sum ./
RUN go mod download

COPY ./ ./

RUN go build -o main.exe

FROM runtime

COPY --from=builder /app/main.exe .
ENTRYPOINT ["main.exe"]
